# Generated by Django 3.1.1 on 2020-09-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rooms', models.TextField()),
                ('monthly_amount', models.TextField()),
                ('guarantee', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('photos', models.TextField()),
                ('state', models.TextField()),
                ('pets', models.BooleanField()),
                ('kids', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
